// The approved storyboard (data/storyboard.json, generated by analysis/storyboard.py): per plate the exact shot times,
// what each shot shows, the beat mechanism, lyric surface, tier and exit. Plate modules' .shots.ts files build their
// structural states on these times (they may add shots, never drop or move one). Pure: safe to import from the gate.
import sb from '@root/data/storyboard.json';

export interface SbShot { t: number; anchor: string; desc: string }
export interface SbPlate {
  id: string; module: string; variant: string; start: number; end: number; lines: number[];
  tier: 'T1' | 'T2' | 'T3'; ground: 'ink' | 'bone'; accent: boolean; beat: string; lyric: string; exit: string; event: string;
  shots: SbShot[];
}

const BY_ID = new Map<string, SbPlate>((sb as { plates: SbPlate[] }).plates.map((p) => [p.id, p]));

/** The storyboard entry for a plate id (throws if the plate isn't in the approved storyboard). */
export function sbPlate(id: string): SbPlate {
  const p = BY_ID.get(id);
  if (!p) throw new Error(`plate not in storyboard: ${id}`);
  return p;
}

/** The approved shot times of a plate, ascending. */
export const sbShotTimes = (id: string) => sbPlate(id).shots.map((s) => s.t);
