"""Music analysis -> data/audio.json (the renderer's AudioData format).

Tempo/beat grid from librosa's beat tracker on the drum stem, refitted to a constant tempo (least squares
over the tracked beats); downbeat phase = the beat offset (mod 4) whose beats carry the most kick energy.
Envelopes at 100 fps (46 ms RMS, 10 ms attack / 90 ms release, each normalised by its 99th percentile).
Onsets from the drum stem: kick = <120 Hz attacks, snare = 1.5-5 kHz attacks, hat = >7 kHz attacks.
Sections: named from the lyric timing (data/lyrics.json) and the energy curve, snapped to downbeats.
"""
import common
import json
import numpy as np
import librosa
import soundfile as sf

FPS = 100
SR = 22050


def env(y, sr, band=None):
    hop = sr // FPS
    if band:
        S = np.abs(librosa.stft(y, n_fft=2048, hop_length=hop))
        f = librosa.fft_frequencies(sr=sr, n_fft=2048)
        m = (f >= band[0]) & (f < band[1])
        e = np.sqrt((S[m] ** 2).mean(axis=0))
    else:
        e = librosa.feature.rms(y=y, frame_length=1024, hop_length=hop)[0]
    out = np.zeros_like(e)
    a, r = 1 - np.exp(-1 / (0.010 * FPS)), 1 - np.exp(-1 / (0.090 * FPS))
    v = 0.0
    for i, x in enumerate(e):
        v += (x - v) * (a if x > v else r)
        out[i] = v
    p = np.percentile(out, 99) or 1
    return np.clip(out / p, 0, 1)


def onsets(y, sr, band, delta):
    hop = 256
    S = np.abs(librosa.stft(y, n_fft=1024, hop_length=hop))
    f = librosa.fft_frequencies(sr=sr, n_fft=1024)
    m = (f >= band[0]) & (f < band[1])
    flux = np.maximum(0, np.diff(np.log1p(100 * S[m]), axis=1)).sum(axis=0)
    flux = np.concatenate([[0], flux])
    flux /= np.percentile(flux, 99.5) or 1
    pk = librosa.util.peak_pick(flux, pre_max=3, post_max=3, pre_avg=10, post_avg=10, delta=delta, wait=6)
    t = librosa.frames_to_time(pk, sr=sr, hop_length=hop)
    return [[round(float(a), 3), round(float(min(1, b)), 3)] for a, b in zip(t, flux[pk])]


def main():
    mix, _ = librosa.load(common.WAV, sr=SR, mono=True)
    dur = len(mix) / SR
    stems = {k: common.load_stem(k, sr=SR)[0] for k in ["vocals", "drums", "bass", "other"]}
    drums = stems["drums"]

    # constant tempo: the period (and phase) at which the strong kick attacks are most phase-coherent
    # (librosa's tracker drifts through the drum-less passages; kicks here are syncopated and a bass
    # line leaks into the <120 Hz band, so only strong attacks vote)
    kicks = onsets(drums, SR, (20, 120), 0.12)
    kt = np.array([t for t, s in kicks if s > 0.4])
    coh = lambda bpm: np.exp(2j * np.pi * kt / (60 / bpm)).mean()
    bpms = np.arange(80, 180, 0.01)
    bpm = float(bpms[np.argmax([abs(coh(b)) for b in bpms])])
    period = 60 / bpm
    t0 = (np.angle(coh(bpm)) / (2 * np.pi)) % 1 * period
    grid = np.arange(t0, dur, period)
    kick_env = env(drums, SR, (20, 120))
    score = [sum(kick_env[min(int(t * FPS), len(kick_env) - 1)] for t in grid[o::4]) for o in range(4)]
    off = int(np.argmax(score))
    downbeats = grid[off::4]

    features = {
        "rms": env(mix, SR), "low": env(mix, SR, (20, 150)), "mid": env(mix, SR, (150, 2000)),
        "high": env(mix, SR, (4000, 11000)),
        **{k: env(v, SR) for k, v in stems.items()},
    }
    ons = {
        "kick": onsets(drums, SR, (20, 120), 0.12),
        "snare": onsets(drums, SR, (1500, 5000), 0.15),
        "hat": onsets(drums, SR, (7000, 11000), 0.12),
        "vocal": onsets(stems["vocals"], SR, (200, 4000), 0.15),
    }

    # sections: lyric-driven verse/bridge windows, the gaps between them are drops/hooks
    ly = json.loads((common.DATA / "lyrics.json").read_text())["lines"]
    snap = lambda t: float(downbeats[np.argmin(np.abs(downbeats - t))])
    def at(i):
        return ly[i]["start"]
    rough = [
        ("intro", 0.0),
        ("verse1", at(0) - 0.3),
        ("pre1", at(8)),
        ("drop1", ly[13]["end"] + 1.0),
        ("bridge", at(14) - 1.0),
        ("verse2", at(17)),
        ("pre2", at(24)),
        ("climax", at(28)),
        ("drop2", ly[-1]["end"] + 1.0),
        ("outro", dur - 30.0),
    ]
    starts = [0.0] + [snap(t) for _, t in rough[1:]]
    sections = [dict(name=n, start=round(s, 3), end=round(e, 3)) for (n, _), s, e in zip(rough, starts, starts[1:] + [dur])]

    doc = dict(
        duration=round(dur, 3), bpm=round(60 / period, 3), beat_period=round(float(period), 5), time_signature=4,
        beats=[round(float(t), 3) for t in grid], downbeats=[round(float(t), 3) for t in downbeats],
        sections=sections, fps=FPS,
        **{k: [round(float(x), 3) for x in v] for k, v in features.items()},
        onsets=ons,
        notes="Generated by analysis/analyze.py (librosa beat tracking on the Demucs drum stem, constant-tempo refit).",
    )
    (common.DATA / "audio.json").write_text(json.dumps(doc))
    print(f"coherence {abs(coh(bpm)):.3f}")
    print(f"dur {dur:.2f}s bpm {60 / period:.3f} first beat {t0:.3f} downbeat offset {off} (scores {np.round(score, 1)})")
    print({k: len(v) for k, v in ons.items()})
    for s in sections:
        print(f"  {s['name']:8s} {s['start']:7.2f} {s['end']:7.2f}")
    # beat-grid sanity: median |kick - nearest beat|
    kt = np.array([o[0] for o in ons["kick"] if o[1] > 0.4])
    d = np.abs(kt[:, None] - grid[None, :]).min(1)
    print(f"strong kicks {len(kt)}, median dist to grid {np.median(d) * 1000:.0f} ms, 90% {np.percentile(d, 90) * 1000:.0f} ms")


if __name__ == "__main__":
    main()
