"""The 4-second summary (docs/SCENES-V3-4S.md): for each 4 s window start (0, 4, 8, ... 232) the plate, idiom, family,
ground, palette, subject and camera/motion in effect, from data/edit.json + data/storyboard.json (the same instants
as the animatic contact sheet). Prints the adjacent-window stats: how many windows share ground / family / idiom
with the previous window, raw and excluding consecutive windows inside the same plate (a plate up to 4 bars = 9.3 s
spans 2-3 windows, which is not a repeat)."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
E = json.loads((ROOT / "data/edit.json").read_text())
SB = {p["id"]: p for p in json.loads((ROOT / "data/storyboard.json").read_text())["plates"]}
DUR = E["duration"]


def at(t):
    p = next(x for x in E["plates"] if x["start"] <= t < x["end"])
    sb = SB[p["id"]]
    sh = [s for s in sb["shots"] if s["t"] <= t + 1e-6][-1]
    return p, sb, sh


def main():
    rows, prev = [], None
    keys = ("ground", "family", "idiom")
    raw = dict.fromkeys(keys, 0)
    cross = dict.fromkeys(keys, 0)
    ncross = 0
    for k in range(int(DUR // 4) + 1):
        t = min(4 * k, DUR - 0.05)
        p, sb, sh = at(t)
        lk = p["look"]
        cur = dict(id=p["id"], ground=lk["ground"], family=lk["family"], idiom=lk["idiom"])
        if prev:
            same_plate = prev["id"] == cur["id"]
            if not same_plate:
                ncross += 1
            for key in keys:
                if prev[key] == cur[key]:
                    raw[key] += 1
                    if not same_plate:
                        cross[key] += 1
        prev = cur
        subj = sb["subject"]
        rows.append(f"| {4 * k:>3} | #{p['n']} `{p['id']}` | {lk['idiom']} | {lk['family']} | {lk['ground']} | `{lk['palette']}` | "
                    f"{subj['kind']} @({subj['x']},{subj['y']}) | `{sh['cam']}`: {sh['desc']} |")
    n = len(rows)
    stats = [f"- windows: {n}; window pairs: {n - 1}; pairs that cross a plate boundary: {ncross}",
             "- same as the previous window (raw, all pairs): " + ", ".join(f"{k} {raw[k]}/{n - 1}" for k in keys),
             "- same as the previous window (pairs across a plate cut only): " + ", ".join(f"{k} {cross[k]}/{ncross}" for k in keys)]
    md = ["# v3 scenes every 4 seconds — generated by analysis/scenes4s.py (do not edit by hand)", "",
          "What is on screen at each 4 s window start (the instants of the animatic contact sheet). Sources: data/edit.json "
          "(plate, look) and data/storyboard.json (subject, shot in effect). `#n` = PLAN-V3 row (#36 is deleted).", "",
          "## Adjacent-window stats", "", *stats, "",
          "Same-idiom pairs across a cut happen only inside the declared sequences (pop-up life #18→#19, demo #39→#41); "
          "a raw repeat inside one plate is the same plate continuing.", "",
          "## Table", "",
          "| t (s) | plate | idiom | fam | ground | palette | subject | camera / motion (shot in effect) |",
          "|---|---|---|---|---|---|---|---|", *rows, ""]
    (ROOT / "docs/SCENES-V3-4S.md").write_text("\n".join(md))
    print("\n".join(stats))


if __name__ == "__main__":
    main()
